server:
  port: 8002
  tomcat:
    max-threads: 1000
    min-spare-threads: 30
  servlet:
    context-path: /
lx:
  dataSource:
    write:
      username: root
      password: 123456
      jdbcUrl: jdbc:mysql://192.168.118.82:3306/ngt?serverTimezone=UTC
      jdbcPool:
        maximumPoolSize: 30
        driverClassName: com.mysql.jdbc.Driver
      configLocation: classpath:mybatis/mybatis-config.xml
      basePackage: com.lx.*.mapper
      typeAliasesPackage: com.lx.*.entity
      mapperLocations: classpath:mybatis/mappers/*/*Mapper.xml
  pagehelper:
    pageSizeZero: true
  swagger: true
  web:
    springmvc:
      cors:
        allow-headers: '*'