server:
  port: 9003
  tomcat:
    max-threads: 1000
    min-spare-threads: 30
  servlet:
    context-path: /back
management:
  endpoints:
    web:
      exposure:
        include:
        - beans
        - info
        - env
        - mappings
        - health
logging:
  config: classpath:logback-spring.xml
  file: D:/logs/springboot.log
lx:
  api:
    url:
      sso: http://sso.huaxing.com/
      ngt: http://ngt.huaxing.com/ngt/
      file: http://file.huaxing.com/upload
      center: http://sale.huaxing.com/
      socket: ws://127.0.0.1:8080/broker/websocket/